sudo: true
language: node_js
node_js:
  - "0.12"
before_install:
  - npm install velocity-ci
script:
  - bash test.sh
services:
  - mongodb
env:
  - LAIKA_OPTIONS="-t 5000"

deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.18f.gov
  username: deploy-agile-bpa
  password:
    secure: "lrkVO8ZKhQBjgSoK6TitB99SP+is/RGFHTC1qvijEBmuP6x1txbWkSDbns78eLfJtiu1oifDa63L7zMiMUC7VwYHn5I5xUltrsd0FR3CeDBu0UCZqk47S8gaFfGEaWgnOCqYC6hTcFZc2GGNKGR+auJ5jnB+Esjfw17UyUoS5lAgh6PireHRZra9KdmRvnxGW2CmJrwsmUFSISn0YvJbJhtxL0ciYlAPSDCSoGQj607RKhepqkTMVfppYpxgha08spaRJo+X0s2QBIDI21EgH8moJx9FhK9uk0l4YNPeyRXLCwuEuhc/v9nXTAe8a6CT4R1kNDPgc77HKIj8SToL7HBsHTptX1ZIDsQzfVYDuCuGM0eWlU0aZcnm3xnounZEdK+ROSlXNAlWx2Ek0yU2NbHi0CMxmhpID1+DmyWkqRye55hdZSD+CNuBj5G9GrHrSd1iO+PcNMBPhIQUDPkknQMRoC7RZsdQkgc3TswBflnbxW5oEZPIOfs3762qLdhYwrX5hV5cVhqjZj/DqX6GTHqoezHCMST4MNGAKKvZg/Fqbu8TpTnOfNQnd1ej55BmI1j6pEL50mqcDvtsPuklaMnbgDTiDaJ9bg0/c7aaVUdSE4w0Lpqt5iOkXeeI0uzdnOPhJ0A8s8oIN3dp7JVWp0KdSJgppq+Y6F7t+JBsp4A="
  organization: agile-bpa
  space: production
  on:
    branch: master
before_deploy:
- echo "deploy on the way"
after_success:
- echo "success!"



